---
- name: Run Docker Compose
  hosts: local

  tasks:
    - name: Install Docker Compose
      # become: true
      apt:
        name: docker-compose
        state: present
    
    # - name: Copy Docker Compose file
    #   copy:
    #     src: ./docker-compose.yml
    #     dest: /home/avi/Desktop/spe/finance-tracker/docker-compose.yml

    - name: Start Docker Compose services
      # become: true
      command: docker-compose up -d
      args:
        chdir: /home/avi/Desktop/spe/finance-tracker/